### ISSUE TITLE
npm Install failed by phantomjs-1.9.7-macosx.zip

### ISSUE THREAD

**Issue by EasonWang01** [GitbookIO/gitbook-pdf#23]
<img width="1127" alt="2017-02-13 5 17 44" src="https://cloud.githubusercontent.com/assets/11001914/22877460/76b02d66-f210-11e6-9f41-047e3e23f003.png">

**Comment by apremalal** [comment]
I'm also facing the same issue here. Seems the phantomjs version is not compatible with the latest node version.
```
2537 verbose stack Error: phantomjs@1.9.7-5 install: `node install.js`
2537 verbose stack Exit status 1
2537 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
2537 verbose stack     at emitTwo (events.js:106:13)
2537 verbose stack     at EventEmitter.emit (events.js:194:7)
2537 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
2537 verbose stack     at emitTwo (events.js:106:13)
2537 verbose stack     at ChildProcess.emit (events.js:194:7)
2537 verbose stack     at maybeClose (internal/child_process.js:899:16)
2537 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
2538 verbose pkgid phantomjs@1.9.7-5
2539 verbose cwd /Users/ag/git/apps-for-proceq-specifications
2540 error Darwin 16.6.0
2541 error argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "install" "gitbook-pdf" "-g"
2542 error node v7.9.0
2543 error npm  v4.2.0
2544 error code ELIFECYCLE
2545 error errno 1
2546 error phantomjs@1.9.7-5 install: `node install.js`
2546 error Exit status 1
2547 error Failed at the phantomjs@1.9.7-5 install script 'node install.js'.
2547 error Make sure you have the latest version of node.js and npm installed.
2547 error If you do, this is most likely a problem with the phantomjs package,
2547 error not with npm itself.
2547 error Tell the author that this fails on your system:
2547 error     node install.js
2547 error You can get information on how to open an issue for this project with:
2547 error     npm bugs phantomjs
2547 error Or if that isn't available, you can get their info via:
2547 error     npm owner ls phantomjs
2547 error There is likely additional logging output above.
2548 verbose exit [ 1, true ]
```

**Comment by i5ting** [comment]
the same issue

**Comment by i5ting** [comment]
- clone code
- npm i -S phantomjs@2.1
- npm link
